# Generated by Django 6.0.7 on 2026-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, choices=[('A', 'Batch A'), ('B', 'Batch B')], max_length=10, null=True),
        ),
    ]
