# Generated by Django 6.0.7 on 2026-08-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
    ]
